Send-only accounts (currently login via IMAP/POP is possible)

diff --git a/assets/admin/users b/assets/admin/users
--- a/assets/admin/users
+++ b/assets/admin/users
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 usage() {
-  echo "usage: ${0} -l | -a <user@domain.xx[:password] | -p <user@domain.xx:password> | -q <user@domain.xx:quota-in-bytes> | -d <user@domain.xx> | -D <user@domain.xx>"
+  echo "usage: ${0} -l | -a <user@domain.xx[:password] | -p <user@domain.xx:password> | -q <user@domain.xx:quota-in-bytes> | -s|S <user@domain.xx> | -d <user@domain.xx> | -D <user@domain.xx>"
 }
 
 if [ -x ${SCRIPT_DIR}/db_functions ]; then
@@ -22,7 +22,7 @@ genpasswd() {
 
 # Analyse Commandline
 RET=0
-while getopts ":hla:p:q:d:D:" OPTION; do
+while getopts ":hla:p:q:s:S:d:D:" OPTION; do
   case ${OPTION} in
     l)
       list_users; RET=$?;
@@ -63,7 +63,28 @@ while getopts ":hla:p:q:d:D:" OPTION; do
         esac
       else
         log 0 "Missing Parametes";
-        usage:
+        usage;
+      fi
+      ;;
+    s|S)
+      _MAIL_=$(echo ${OPTARG} | awk 'BEGIN{ FS=":"; }{ print $1; }');
+
+      if [[ -n ${_MAIL_} ]]; then
+        case ${OPTION} in
+          s)
+              log 2 "Mail: ${_MAIL_} / DISABLE";
+              user_update_inboxstate ${_MAIL_} FALSE;
+              RET=$?;
+              ;;
+          S)
+              log 2 "Mail: ${_MAIL_} / ENABLE";
+              user_update_inboxstate ${_MAIL_} TRUE;
+              RET=$?;
+              ;;
+        esac
+      else
+        log 0 "Missing Parametes";
+        usage;
       fi
       ;;
     d)
diff --git a/assets/scripts/db_functions b/assets/scripts/db_functions
--- a/assets/scripts/db_functions
+++ b/assets/scripts/db_functions
@@ -354,7 +354,7 @@ user_update_password() {
 ## return: 0 = Success, >0 = User doesn't exist or other error (see log output)
 user_update_quota() {
   if [[ -z ${1} || -z ${2} ]]; then
-    echo "usage: ${0} <mail-address> <password>"
+    echo "usage: ${0} <mail-address> <quota-in-kb>"
     exit 200;
   fi
 
@@ -364,8 +364,36 @@ user_update_quota() {
     return 1;
   fi
 
-  log 2 "Update User Quota <${1}>"
+  log 2 "Update User Quota <${1}> to <${2} KB>"
   _db_ "$(printf "${QUERY_USER_UPDATE}" "quota_limit" "${2}" "${1}" "${1}")"
+
+  return $?
+}
+
+## Update a User's INBOX state
+## param 1: User's Mail-Address
+## param 2: INBOX state (true = enbled, false = disabled)
+## return: 0 = Success, >0 = User doesn't exist or other error (see log output)
+user_update_inboxstate() {
+  if [[ -z ${1} || -z ${2} ]]; then
+    echo "usage: ${0} <mail-address> <state>"
+    exit 200;
+  fi
+
+  _STATE_=${2,,}
+  if ! [[ ${_STATE_} == "true" || ${_STATE_} == "false" ]]; then
+    echo "ERROR: Only 'true' or 'false' are allowed!"
+    exit 300;
+  fi
+
+  user_exists "${1}"
+  if [ $? -gt 0 ]; then
+    log 0 "User <${1}> doesn't exist!"
+    return 1;
+  fi
+
+  log 2 "Update User INBOX state <${1}> to <${_STATE_}>"
+  _db_ "$(printf "${QUERY_USER_UPDATE}" "receive_mail" "${2}" "${1}" "${1}")"
 
   return $?
 }
